title: tqworld
author: dodoji
email: thiqooo@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  ìš°í•˜í•˜í•˜ ë¹™ê¸€ë¹™ê¸€ ëŒì•„ê°€ëŠ” ë„ë„ì§€ì˜ ì„¸ê³„...
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  navigation:
    - title: ì¼ìƒ
      url: "/ì¼ìƒ"
    - title: ë…ì„œ
      url: "/ë…ì„œ"
    - title: PS
      url: "/PS"
      
  name: dodoji's

  tagline: tq world ğŸš
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/IMG_1378.PNG" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "ko" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    twitter: 1717007
#    github:  samarsault
#    linkedIn: in/samarsault
    #dribbble: jekyll
    #flickr:   jekyll
    instagram: dodojikim
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
#theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

remote_theme: samarsault/plainwhite-jekyll
